// <auto-generated />
using System;
using Esports_Org_Manager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Esports_Org_Manager.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240613181102_castersOrganizers")]
    partial class castersOrganizers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3");

            modelBuilder.Entity("EmployeeTourneysCasters", b =>
                {
                    b.Property<int>("castersid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tourneyCastsid")
                        .HasColumnType("INTEGER");

                    b.HasKey("castersid", "tourneyCastsid");

                    b.HasIndex("tourneyCastsid");

                    b.ToTable("EmployeeTourneysCasters");
                });

            modelBuilder.Entity("EmployeeTourneysOrganised", b =>
                {
                    b.Property<int>("ownOrganizersid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("tourneyParticipationsid")
                        .HasColumnType("INTEGER");

                    b.HasKey("ownOrganizersid", "tourneyParticipationsid");

                    b.HasIndex("tourneyParticipationsid");

                    b.ToTable("EmployeeTourneysOrganised");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.ContractModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isRenegotiable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("membershipId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("signDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("validityPeriod")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("membershipId");

                    b.ToTable("Contracts", (string)null);
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.EmployeeModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("channels")
                        .HasColumnType("TEXT");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("employeeTypeDiscriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("nick")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("numberOfHoursStreamingPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("numberOfVideosPerWeek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("organizationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("placementBonuses")
                        .HasColumnType("TEXT");

                    b.Property<int?>("procentageOfWinnings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("wage")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("organizationName");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.IndependentContractorModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("price")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.ToTable("IndependentContractors", (string)null);
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.MembershipModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("employeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("teamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("employeeId");

                    b.HasIndex("teamId");

                    b.ToTable("Memberships", (string)null);
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.OrganizationModel", b =>
                {
                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("name");

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.TeamModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("creationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("logo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("minimalAgeEligibility")
                        .HasColumnType("INTEGER");

                    b.Property<int>("minimalNumberOfPlayers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("organizationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("region")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("organizationName");

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.TourneyModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("adress")
                        .HasColumnType("TEXT");

                    b.Property<double>("awardPool")
                        .HasColumnType("REAL");

                    b.Property<string>("competitionType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("date")
                        .HasColumnType("TEXT");

                    b.Property<string>("format")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("independentOrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("organizerDiscriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("procentPerPlace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("streamLinks")
                        .HasColumnType("TEXT");

                    b.Property<double?>("ticketPrice")
                        .HasColumnType("REAL");

                    b.Property<string>("viewTypeDiscriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("independentOrganizerId");

                    b.ToTable("Tourneys", (string)null);

                    b.HasDiscriminator<string>("competitionType").HasValue("TourneyModel");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.SoloTourneyModel", b =>
                {
                    b.HasBaseType("Esports_Org_Manager.Models.TourneyModel");

                    b.Property<bool>("allowCoaching")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("solo");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.TeamTourneyModel", b =>
                {
                    b.HasBaseType("Esports_Org_Manager.Models.TourneyModel");

                    b.Property<int>("playerChangePointsPenalty")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("team");
                });

            modelBuilder.Entity("EmployeeTourneysCasters", b =>
                {
                    b.HasOne("Esports_Org_Manager.Models.EmployeeModel", null)
                        .WithMany()
                        .HasForeignKey("castersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Esports_Org_Manager.Models.TourneyModel", null)
                        .WithMany()
                        .HasForeignKey("tourneyCastsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeTourneysOrganised", b =>
                {
                    b.HasOne("Esports_Org_Manager.Models.EmployeeModel", null)
                        .WithMany()
                        .HasForeignKey("ownOrganizersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Esports_Org_Manager.Models.TourneyModel", null)
                        .WithMany()
                        .HasForeignKey("tourneyParticipationsid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.ContractModel", b =>
                {
                    b.HasOne("Esports_Org_Manager.Models.MembershipModel", "membership")
                        .WithMany("contracts")
                        .HasForeignKey("membershipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("membership");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.EmployeeModel", b =>
                {
                    b.HasOne("Esports_Org_Manager.Models.OrganizationModel", "organization")
                        .WithMany("employees")
                        .HasForeignKey("organizationName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organization");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.MembershipModel", b =>
                {
                    b.HasOne("Esports_Org_Manager.Models.EmployeeModel", "employee")
                        .WithMany("memberships")
                        .HasForeignKey("employeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Esports_Org_Manager.Models.TeamModel", "team")
                        .WithMany("memberships")
                        .HasForeignKey("teamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("employee");

                    b.Navigation("team");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.TeamModel", b =>
                {
                    b.HasOne("Esports_Org_Manager.Models.OrganizationModel", "organization")
                        .WithMany("teams")
                        .HasForeignKey("organizationName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("organization");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.TourneyModel", b =>
                {
                    b.HasOne("Esports_Org_Manager.Models.IndependentContractorModel", "independentOrganizer")
                        .WithMany("tourneys")
                        .HasForeignKey("independentOrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("independentOrganizer");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.EmployeeModel", b =>
                {
                    b.Navigation("memberships");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.IndependentContractorModel", b =>
                {
                    b.Navigation("tourneys");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.MembershipModel", b =>
                {
                    b.Navigation("contracts");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.OrganizationModel", b =>
                {
                    b.Navigation("employees");

                    b.Navigation("teams");
                });

            modelBuilder.Entity("Esports_Org_Manager.Models.TeamModel", b =>
                {
                    b.Navigation("memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
